import type { Metadata } from "next";
import "~/styles/globals.css";
import { ThemeProvider } from "~/components/theme-provider";
import Header from "~/components/header";
import React from "react";
import Footer from "~/components/footer";
import { ClerkProvider } from "@clerk/nextjs"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`antialiased min-h-screen relative`}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Header></Header>
            {children}
            <Footer></Footer>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
